interface: wlan1               # Your wireless interface in monitor mode
log_path: logs/wifi_attack_logs.db # Path to your SQLite log database
scan_interval: 2                   # Interval (seconds) for scanning (if used)
block_method: nftables             # Firewall method (nftables recommended on modern Linux)
firewall_host: 127.0.0.1           # Host for firewall server
firewall_port: 9000                # Port for firewall server
socket_timeout: 5                  # Timeout for socket operations (seconds)
api_port: 5000                     # Port for Flask API server
debug: true                        # Enable Flask debug mode
log_level: INFO                    # Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
